---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokenizer
  labels:
    app: tokenizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokenizer
  template:
    metadata:
      labels:
        app: tokenizer
    spec:
      containers:
      - name: tokenizer
        image: andriygav/processing-docker:latest
        ports:
        - containerPort: 9878
          name: grpc
          protocol: TCP
        - containerPort: 9999
          name: metrics
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tokenizer
  labels:
    app: tokenizer
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 9878
    protocol: TCP
  - name: metrics
    port: 9999
    protocol: TCP
  selector:
    app: tokenizer
---
apiVersion: v1
kind: Service
metadata:
  name: tokenizer-np
spec:
  type: NodePort
  selector:
    app: tokenizer
  ports:
  - name: grpc
    port: 9878
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tokenizer
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: tokenizer
  endpoints:
  - port: metrics
    interval: 15s