{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "tokenizer.labels" . | nindent 4 }}
  name: {{ template "tokenizer.name" . }}
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ template "tokenizer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end -}}